### ISSUE TITLE
Vue.js and Cosmos integration issue

### ISSUE THREAD

**Issue by softtscoder** [softtscoder/blog-ignite-cosmosSdk#1]
Ran into a bit of a problem with combining Laravel and Vue.js to populate a table.

Essentially, I was trying to use the v-repeat property in combination with a http:get request using the vue-resources extension. The problem is that no values appear to be getting passed through by Vue - I simply get the {{first_name}} and {{email_address}} in brackets.

I can confirm that the API method that is called by the http:get request is in fact spitting out data (manually accessing the URL in the browser reveals data).

Here is the code in the routes.php file that is responsible for outputting the data:

```
get('api/v1_users',function()
{
    return App\User::all()->toJson();
});
```
Here is the accompanying javascript file with the Vue.js code: (main.js)

```
new Vue({
    el: "#user",

    data:
    {
        v1_user:[],
    },

    ready : function()
    {
        this.fetchV1IntermediaryUsers();
    },

    methods:
    {
        fetchV1IntermediaryUsers: function() {
            this.$http.get('/api/v1_users',function(v1users) {
                this.$set('v1_user',v1users);
            });

        }
    }
});
```

**Comment by C3261226** [comment]
Check your browser console and post if there are any errors.

**Comment by softtscoder** [comment]
Added a screenshot above!

**Comment by C3261226** [comment]
You have two different sections with the same id user. One section won't be affected by Vue. Try different instances with different ids or other method. Are you getting one section correctly or neither one.

**Comment by C3261226** [comment]
You have multiple DIV's with the same ID's. ID's in HTML must be unique. When you start a VUE instance you bind it to an element, in this case which is in your code twice. Remove the ID's and add an ID to the <Body> tag, then check your code.

**Comment by withts** [comment]
Though, my last idea would be that it is because the element I'm referencing is the parent of v-repeat element (v1_user), but the actual data is being spit out under the <td> tags. Would this matter? Can the children of the v-repeat element access the data without any special tags or modifiers?

**Comment by softtscoder** [comment]
> You have multiple DIV's with the same ID's. ID's in HTML must be unique. When you start a VUE instance you bind it to an element, in this case which is in your code twice. Remove the ID's and add an ID to the tag, then check your code

Thank you for your answer
